# Generated by Django 3.0.3 on 2020-03-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_head', models.CharField(max_length=225)),
                ('news_web', models.CharField(max_length=225)),
                ('Date', models.DateField()),
            ],
        ),
    ]
