# Generated by Django 3.0.3 on 2020-03-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='news_web',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
